server:
 port: 8081

spring:
 application:
  name: payment-service
 cloud:
  config:
   profile: dev
 config:
  import: configserver:http://localhost:8071
 jpa:
   hibernate:
     ddl-auto: update
   properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true